#!/bin/sh

# This script executes a teragen and terasort with Hadoop 2.0.  It is
# an example of how you can setup a script to run Hadoop job.  It is
# set via the HADOOP_SCRIPT_PATH environment variable and setting the
# HADOOP_MODE to 'script'.  See the job submission file for details.
#
# Please adjust to whatever you would want to do with Hadoop

echo "Running wordcount script."

export JAVA_HOME="/software6/compilers/java/1.8.0_40/"
export HADOOP_HOME="/software6/apps/hadoop/2.5.2"

export PATH=$JAVA_HOME/bin:$PATH
export WORKDIR=${HOME}/tp5/wordcount
export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:$JAVA_HOME/lib/tools.jar

echo "CD to WORKDIR"
cd $WORKDIR

#--->now in compile.sh
#$HADOOP_HOME/bin/hadoop com.sun.tools.javac.Main *.java
#jar cf wc.jar *.class
#export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:${WORKDIR}/wc.jar


echo "CD to HADOOP_HOME"
cd $HADOOP_HOME

bin/hdfs dfs -mkdir -p /user/$USER/tp5/wordcount
command="bin/hdfs dfs -copyFromLocal ${WORKDIR}/input /user/$USER/tp5/wordcount/"
echo "Running $command" >&2
$command

command="bin/hdfs dfs -ls /user/$USER/tp5/wordcount/input"
echo "Running $command" >&2
$command

command="bin/hadoop jar ${WORKDIR}/wc.jar WordCount /user/$USER/tp5/wordcount/input /user/$USER/tp5/wordcount/output"
echo "Running $command" >&2
$command

command="bin/hdfs dfs -copyToLocal /user/$USER/tp5/wordcount/output $WORKDIR/output"
echo "Running $command" >&2
$command

exit 0
